### ISSUE TITLE
Numba error with VELOCIraptor integration

### ISSUE THREAD

**Issue by filipello** [SWIFTSIM/swiftsimio#105]
Hello,
I'm a student working with Matthieu Schaller and after following the example code proposed here https://swiftsimio.readthedocs.io/en/latest/velociraptor/index.html (I just replaced the data from the FLAMINGO simulation instead of the toy model) I got a very long error related to Numba with this final message:

-------------------------------------------------
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
iterating over 2D array

File "../.local/lib/python3.6/site-packages/swiftsimio/accelerated.py", line 247:
def get_chunk_ranges(
    <source elided>
    n_ranges = len(ranges)
    for bounds in ranges:
    ^

[1] During: lowering "$18.2 = iternext(value=$phi18.1)" at /home/filipello/.local/lib/python3.6/site-packages/swiftsimio/accelerated.py (247)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
-------------------------------------------------

Is this strictly related to the SWIFTsimIO package or should I ask on the Numba Gituhub?

Thanks in advance

**Comment by bwvdnbro** [comment]
What version of Numba are you using? And on what machine? Similar looking numba errors in the past were caused by old numba versions and weird things happening with module versions on the observatory machines. In that case, something as simple as `module load Python` to load a more recent Python version and then manually `pip` installing a recent numba version fixes the issue.

**Comment by filipello** [comment]
I get this error when working on the quasar machine. I tried your suggestions but I still get the same error...

**Comment by bwvdnbro** [comment]
Could you share the location of your script? I will have a look. swiftsimio is definitely supposed to work on quasar, but there have been numba issues on quasar before.
That being said, it could be that using the FLAMINGO dataset triggers an actual issue in swiftsimio, so it is worth investigating.

**Comment by filipello** [comment]
/home/filipello/python notebook/Test_script.ipynb
It's really just a copy-paste of the example. Anyway this problem does not appear on the STRW desktop computers, but just with quasar.

**Comment by bwvdnbro** [comment]
How are you running the notebook on quasar?

If it runs on other machines, then it is not a swiftsimio issue.

**Comment by bwvdnbro** [comment]
Also, I don't have permissions to access your home folder, so I can't have a look at the script.

Could you please try:
 - putting the script in a plain `.py` file
 - loading a non-default Python version on quasar (`module load Python`)
 - running the `.py` script manually via the command line (using `python3`)

If that does not work, please let me know the following:
 - Python version (`python3 --version`)
 - The numba version (`python3 -c "import numba; print(numba.__version__)"`)

I suspect you are somehow still running Python 3.6.8 and numba 0.42.1, for which there are known problems. Loading the Python module should make Python 3.8.6 and numba 0.54.1 available.

**Comment by filipello** [comment]
After loading the recent versions of Python and Numba the file in format .py seems to work properly. There are still some problem if I try to run the script on jupyterlab but it's clearly not related to swiftsimio.

**Comment by MatthieuSchaller** [comment]
@bwvdnbro since this keeps happening, should we ask IT to upgrade the python version on the quasar system as well as on "our" other systems?

**Comment by bwvdnbro** [comment]
Not sure that is the best solution. The problem is not so much that the Python version on quasar is old, but rather that quasar *has* a Python installation. If we are supposed to use the module system, then the machines shouldn't also have their own local installation. Because then you get conflicts like this one.

If everyone just uses the modules and manages their own (user-specific) Python modules using PIP, then everything works fine.

And do we really want people to run notebook servers on non-desktop machines?

**Comment by MatthieuSchaller** [comment]
Right, but I guess we can't remove the system-default python there as nowadays nearly everything runs on python.

As for notebooks, I am also not a fan, but looks like everybody else is...

**Comment by Joeybraspenning** [comment]
Matthieu told me to complain here as well. My master student is also having swiftsimio problems on quasar, but all works fine on the strw desktops. It seems he's unable to install swiftsimio on quasar, with some very long error complaining about llvmlite

When I try to install it myself after doing `module load Python` to move away from the default python in which nothing works, I experience some other pip errors:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

numba 0.54.1 requires numpy<1.21,>=1.17, but you'll have numpy 1.21.1 which is incompatible.
```

When doing `import swiftsimio` after this installation (which finishes with the message that everything is succesfully installed despite the error above), the python terminal tells me that numba is not installed.

There's some hdf5 problems on quasar as well, it seems to always have conflicts with the version. Might be a good idea to update the machine to the same configuration as used on the strw desktops, there everything works flawlessly.

**Comment by bwvdnbro** [comment]
`pip install numpy==1.20.3` and then `pip install numba` should do the trick. That is what I am currently using on quasar.

But sure, the Python installation on quasar is messed up. I'll ask the IT guys to update it.

**Comment by bwvdnbro** [comment]
Right, so apparently updating the Python installation (or anything else) on quasar is too much work, but they can upgrade the numba module that goes with it. That should probably do the trick.

Apparently you can also use `python3.8` instead of `python3` to run things with the right Python version, without having to load any modules.

**Comment by Joeybraspenning** [comment]
Ah great, maybe as a small addition to that, this works for me if I install numba with `pip3.8 install numba`
