### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by joe637** [SWIFTSIM/swiftsimio#109]
I am currently trying to plot a 10^7 particle planetary giant impact SWIFT simulation with swiftsimio on python 3.8 but whenever I try to actually read the particle data in the snapshot files it gives a segmentation fault. This strikes me as odd because the first few snapshots are read just fine, but past a certain point the snapshots give this error:

    """ Select and load the particles to plot. """
    # Snapshot to load
    snapshot = "impact_%04d.hdf5" % snapshot_id

    # Only load data with the axis limits and below z=0
    ax_lim = 100
    mask = sw.mask(snapshot)
    box_mid = 0.5 * mask.metadata.boxsize[0].to(unyt.Rearth)
    x_min = box_mid - ax_lim * unyt.Rearth
    x_max = box_mid + ax_lim * unyt.Rearth
    load_region = [[x_min, x_max], [x_min, x_max], [x_min, box_mid]]
    mask.constrain_spatial(load_region)

    # Load
    data = sw.load(snapshot, mask=mask)
    print(data.metadata.gas_properties.field_names)
    pos = data.gas.coordinates.to(unyt.Rearth) - box_mid
    print(pos)

    id = data.gas.particle_ids
    mat_id = data.gas.material_ids.value

What's particularly strange is that if I run each file in succession in a for loop rather than individually, it gives a different error:

Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4350, in _parse_scatter_color_args
    colors = mcolors.to_rgba_array(c)
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/colors.py", line 385, in to_rgba_array
    rgba = np.array([to_rgba(cc) for cc in c])
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/colors.py", line 385, in <listcomp>
    rgba = np.array([to_rgba(cc) for cc in c])
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/colors.py", line 206, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/colors.py", line 284, in _to_rgba_no_colorcycle
    raise ValueError(f"Invalid RGBA argument: {orig_c!r}")
ValueError: Invalid RGBA argument: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "plot_solution.py", line 169, in <module>
    plot_snapshot(pos, mat_id, ax_lim)
  File "plot_solution.py", line 138, in plot_snapshot
    ax.scatter(
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4516, in scatter
    self._parse_scatter_color_args(
  File "/home/joe/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4359, in _parse_scatter_color_args
    raise ValueError(
ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not [0 0 0 ... 'gray' 'saddlebrown' 'saddlebrown']

**Comment by MatthieuSchaller** [comment]
What matplotlib version are you running?

**Comment by joe637** [comment]
3.4.3

**Comment by JBorrow** [comment]
Do you mean there is an actual segmentation fault or that the code quits with an error after raising an exception?

**Comment by JBorrow** [comment]
I'm surprised that `swiftsimio` runs on windows at all. Are you using WSL?

**Comment by JBorrow** [comment]
FWIW, the above seems like you're having problems with rendering it in matplotlib, unrelated to the output from swiftsimio. Can you investigate the data itself?

**Comment by joe637** [comment]
Yeah I can run it on WSL., I don't think its a matplotlib issue because it gives this error if I read the data itself

**Comment by joe637** [comment]
I'm currently trying to install swiftsimio onto hamilton 7 but pip seems to have trouble installing numba

**Comment by joe637** [comment]
python crashes if I run it in a shell terminal, so I think it might be a memory issue

**Comment by JBorrow** [comment]
Can you extract a minimum example that breaks predictably and share the files with us so that we can track this down?

You should speak to the system administrators to get `numba` installed on Hamilton. They can help you.

**Comment by joe637** [comment]
Sorry it's taken me a long time to respond. This now seems to work with h5py alone, but I'm now checking for the minimum number of particles it takes for swiftsimio to break.
