### ISSUE TITLE
Giant Impact simulations stopping

### ISSUE THREAD

**Issue by joe637** [SWIFTSIM/swiftsimio#111]
I am currently running giant impact simulations but when I run simulations with >10^7 particles, the simulations have a tendency to stop at a certain pointy in the simulation. SWIFT still seems to be running with restart files being written, but the SWIFT has stopped doing timesteps, so I get output files like this:

[00004.1] engine_config: Minimal timestep size (on time-line): 8.381903e-05
[00004.1] engine_config: Maximal timestep size (on time-line): 2.746582e+00
[00004.1] engine_config: Restarts will be dumped every 1.000000 hours
[00004.1] engine_config: Using 48 threads in the thread-pool
[00004.1] engine_config: took 64.817 ms.
#   Step           Time Scale-factor     Redshift      Time-step Time-bins      Updates    g-Updates    s-Updates sink-Updates    b-Updates  Wall-clock time [ms]  Props
lfs setstripe: setstripe error for 'restart/swift_000000.rst': Invalid argument
lfs setstripe: setstripe error for 'restart/swift_000000.rst': Invalid argument
lfs setstripe: setstripe error for 'restart/swift_000000.rst': Invalid argument
lfs setstripe: setstripe error for 'restart/swift_000000.rst': Invalid argument

**Comment by mladenivkovic** [comment]
That smells like an issue with the file system. Did you perhaps exceed your quota or something like that? Or did the "restart" directory got removed somehow?

**Comment by joe637** [comment]
The restart directory is still there, and if by quota you mean I ran out of space, there are more than 5TB left at the moment so its probably not that, unless you mean something else.

**Comment by MatthieuSchaller** [comment]
Seems to not be a swiftsimio issue. 

Please post a more detailed log and how things were compiled and ran on the correct github repo.
