### ISSUE TITLE
Giant impact max time steps

### ISSUE THREAD

**Issue by joe637** [SWIFTSIM/swiftsimio#112]
When I run a giant impact simulation in swift with the max and min timesteps as provided by the earth impact example in swift, I seem to run into problems as the planets seem to explode and layers get destroyed. This problem seems when I decrease the maximum timesteps to 10. I'm not quite sure about this because the timesteps don't seem to be too crazy, mainly 2-10s, but they get mainly fixed at 5s when I limit the max dt to 10s. This doesn't seem to happen with the impact example, so I'm not quite sure what could be causing this. This example is with ~10^6 particles

![impact_0331](https://user-images.githubusercontent.com/88051094/156849976-6c8d7694-f7c0-4d4c-a7c6-2310ff4fa23d.png)
![impact_0543](https://user-images.githubusercontent.com/88051094/156850032-e95b6015-4ba1-490a-9f06-69edb4690b1a.png)
.

**Comment by MatthieuSchaller** [comment]
Is that issue on the correct repository? Seems not to be related to the python i/o library.
