### ISSUE TITLE
Non-cubic boxes not supported for slice visualisation

### ISSUE THREAD

**Issue by zorrybelcheva** [SWIFTSIM/swiftsimio#115]
Hi guys,

To my understanding it's currently not possible to make non-square slice images directly. The error returned when e.g. slice_gas() is prompted with a non-cubic box is `Slice code is currently not able to handle non-square images`. 

A way to bypass this is to use slice_scatter(), rescaling the coordinates to [0, 1] and then cutting off the empty parts of the image, or alternatively to stitch together a grid of images, e.g. 2 along the x-direction if using a box of dimensions [2, 1, 1]. I'm wondering if this would be the standard way to approach this?

**Comment by bwvdnbro** [comment]
`slice_gas()` calls `slice_scatter()` internally, so using that function is definitely appropriate. I think the first option (where you rescale and then cut the empty parts of the image) should be faster, so I would recommend that.

I am wondering why this restriction exists. There is no fundamental reason why non-square images would not work. The only problem is that you then need two numbers for the number of pixels, and you risk having incompatible dimensions in the actual image size and the image pixel size.

A quick workaround would be to always produce a square image that has the maximum of the two dimensions as side length. We could then potentially automatically cut empty pixels. That would be the equivalent of your first option.

@JBorrow any thoughts?

**Comment by bwvdnbro** [comment]
@zorrybelcheva you can find a tentative implementation that supports non-cubic boxes in the branch `non-square-slices`. We are still figuring out some subtleties when you use rotations, but if you don't need rotations you can already give this a try.

**Comment by JBorrow** [comment]
Is this now fixed in v5.0.0?

**Comment by MatthieuSchaller** [comment]
@zorrybelcheva could you confirm whether this now works in the latest version?

**Comment by zorrybelcheva** [comment]
Yes! Can confirm there is no error anymore.
