### ISSUE TITLE
boxsize in metadata should be cosmo_array, not unyt_array?

### ISSUE THREAD

**Issue by kyleaoman** [SWIFTSIM/swiftsimio#128]
In `reader.py` the `SWIFTMetadata` object unpacks the `BoxSize` from the header as:
https://github.com/SWIFTSIM/swiftsimio/blob/a157029803f5584585b123421440e85b5e72269c/swiftsimio/reader.py#L371-L373

It would make more sense for this to be a `cosmo_array` (in particular specifying the correct `comoving` flag). I'm in principle happy to make a PR, but after staring at the code for ~15 minutes I can't work out where to put this in. Could be in `reader.py` if this is just to be a one-time exception for the box size, like for the scale factor:
https://github.com/SWIFTSIM/swiftsimio/blob/a157029803f5584585b123421440e85b5e72269c/swiftsimio/reader.py#L534-L539
Or if there are other header fields that similar logic could apply to it would be better placed in `metadata/metadata/metadata_fields.py`?

**Comment by MatthieuSchaller** [comment]
I think this makes sense, yes.
