### ISSUE TITLE
cosmo_array multiplication does not return cosmo_array

### ISSUE THREAD

**Issue by bwvdnbro** [SWIFTSIM/swiftsimio#142]
Merging #137 and #141 unfortunately broke some of the visualisation functions. Consider the following code snippet:
```
data.gas.HI_mass_fraction = (
    data.gas.masses
    * data.gas.element_mass_fractions.hydrogen
    * data.gas.species_fractions.HI
)
HI_map = project_gas(
                    data,
                    resolution=8000,
                    project="HI_mass_fraction",
                )
```
All the `data.gas.XXX` attributes are `cosmo_array`s, but unfortunately `data.gas.HI_mass_fraction` is not, since multiplication of `cosmo_array`s does not conserve the `cosmo` properties. `project_gas` will fail when it tries to confirm that `HI_mass_fraction` and the coordinates are compatible cosmological quantities.

The only way to fix this would be to add support for multiplication (and maybe some other operators) to `cosmo_array`. We probably also want to disable unsupported operations to be on the safe side.

**Comment by kyleaoman** [comment]
#131 is a symptom of the same issue. #132 is nearly ready to merge and will implement all the ufuncs supported for unyt_arrays for use with cosmo_arrays.
