### ISSUE TITLE
unyt requires python>=3.8

### ISSUE THREAD

**Issue by kyleaoman** [SWIFTSIM/swiftsimio#146]
The latest unyt release 2.9.0 requires python>=3.8 (previously >=3.5). This is already rearing its head in #145.

**Comment by MatthieuSchaller** [comment]
The latest release says we are >=3.8.0 but this line seems to say we still support 3.7.0

https://github.com/SWIFTSIM/swiftsimio/blob/ce864e3189833191bee673d6672bd884884a21a8/setup.py#L20

**Comment by bwvdnbro** [comment]
I'll let @JBorrow sort this out, because I'm not really familiar with how `setup.py` works.

**Comment by JBorrow** [comment]
Those classifiers are not actually used by setup.py. Those are just published on the pypi webpage. I've changed the setup.py to include a `python_requires` that will go out the next time we rev a version. This issue has also caused me some issues...
