### ISSUE TITLE
`RuntimeError: Unexpected state, please report this error on github.`

### ISSUE THREAD

**Issue by mladenivkovic** [SWIFTSIM/swiftsimio#149]
```
$ ./rt_sanity_checks-GEAR.py 
checking essentials
Traceback (most recent call last):
  File "./rt_sanity_checks-GEAR.py", line 376, in <module>
    main()
  File "./rt_sanity_checks-GEAR.py", line 369, in main
    check_essentials(snapdata, rundata)
  File "./rt_sanity_checks-GEAR.py", line 146, in check_essentials
    fishy = groupfluxnorm > max_fluxes
  File "/home/mivkov/local/swiftsimio/swiftsimio/objects.py", line 1037, in __array_ufunc__
    ret_cf = self._cosmo_factor_ufunc_registry[ufunc](*cfs, inputs=inputs)
  File "/home/mivkov/local/swiftsimio/swiftsimio/objects.py", line 356, in _comparison_cosmo_factor
    return _return_without_cosmo_factor(
  File "/home/mivkov/local/swiftsimio/swiftsimio/objects.py", line 297, in _return_without_cosmo_factor
    raise RuntimeError("Unexpected state, please report this error on github.")
RuntimeError: Unexpected state, please report this error on github.
```

Problem is reproducible for the `examples/RadiativeTransferTests/UniformBox_3D` test example when running `rt_sanity_checks-GEAR.py` (this script is not automatically called by `run.sh`)

To run that example, you'd need to configure with `--with-rt=GEAR_3 --with-rt-riemann-solver=GLF --with-hydro-dimension=3 --with-hydro=gizmo-mfv --with-riemann-solver=hllc --with-stars=basic --with-feedback=none`

**Comment by MatthieuSchaller** [comment]
Is that still an issue?

**Comment by MatthieuSchaller** [comment]
@mladenivkovic is that still a problem?

**Comment by kyleaoman** [comment]
Hi @mladenivkovic, happy to try to squash this bug (if it still exists), except that I can't get swift + grackle to compile. Do you have a module setup and config arguments that work on current cosma?

**Comment by mladenivkovic** [comment]
Hi!
Just tried it again with an up-to-date swift and swiftsimio. The issue seems to be resolved. Sorry this went under my radar for so long!
