### ISSUE TITLE
Python 3.12 ?

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/swiftsimio#181]
Are there any reasons why the installer refuses to deploy on python 3.12? Does the code need adapting for that version?

**Comment by JBorrow** [comment]
What error message do you get? That should not happen. We do not explicitly gate against it.

**Comment by MatthieuSchaller** [comment]
We do here: https://github.com/SWIFTSIM/swiftsimio/blob/55fe0061d6e41f25b2291a209439149f2cffeaaf/pyproject.toml#L17

**Comment by JBorrow** [comment]
Was that your only concern? Please let me know if the install actually breaks and we can fix it. On my end I do not think there are any problems.

**Comment by JBorrow** [comment]
Likely due to incompatibilities in llvmlite and numba or something. Numba only recently supported 3.12 as there were a few changes.

**Comment by JBorrow** [comment]
P.S. tests now all run on 3.12 as well.
