### ISSUE TITLE
Add warning when the cosmology can't be represented correctly?

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/swiftsimio#183]
We currently rely on astropy cosmology but this is not general enough to handle the default flamingo/colibre cosmologies. Should we add a warning when we load anything that is not a flat neutrino-free LCDM model?

**Comment by kyleaoman** [comment]
Why isn't it general enough? The astropy `FLRW` class can handle arbitrary non-flat cosmologies with massive neutrinos, which seems like it should be enough. https://docs.astropy.org/en/stable/api/astropy.cosmology.FLRW.html#astropy.cosmology.FLRW

**Comment by kyleaoman** [comment]
Also time-varying DE cosmologies: https://docs.astropy.org/en/stable/cosmology/ref_api.html

**Comment by MatthieuSchaller** [comment]
mmmh has this changed astropy-side recently? I recall issues at least at the start of flamingo with the neutrino side of things. Might be mute now.

**Comment by kyleaoman** [comment]
As far as I remember it's been like this for a long time - quick look at astropy history suggests massive neutrinos were in the initial cosmology module in 2015.

**Comment by MatthieuSchaller** [comment]
Then I am wrong about it and have been for a long time.
