### ISSUE TITLE
Adding material ID attribute

### ISSUE THREAD

**Issue by yonatansmn** [SWIFTSIM/swiftsimio#50]
Hi,
I'm running a planetary simulation, how do I add material IDs property?

thanks

**Comment by JBorrow** [comment]
Do you mean in the initial conditions that you are creating with `SWIFTWriter`? Or reading things out of snapshots?

**Comment by yonatansmn** [comment]
when I create ICs with SWIFTWriter

**Comment by JBorrow** [comment]
So I've taken a look at this and it appears that it's going to be difficult to make it work with material ids easily.

I would suggest creating the snapshot with the `SWIFTWriter` and then adding manually the Material IDs after:

```python
# SWIFTWriter stuff...

with h5py.File("my_snapshot_filename.hdf5", "r") as handle:
    handle["/PartType0"].create_dataset("MaterialIDs", data=material_ids)
```

Sorry that this isn't easier to do, we should revisit that code soon.

**Comment by yonatansmn** [comment]
Thanks.

**Comment by JBorrow** [comment]
You should also be careful to make sure that your initial smoothing lengths are ok - the automatic generation assumes a cosmological type code, where particles are spread evenly throughout the box. You can use the tree available in https://swiftsimio.readthedocs.io/en/latest/modules/swiftsimio.visualisation.smoothing_length_generation.html that will allow you to find correct ones based on your particle distribution.

**Comment by yonatansmn** [comment]
Thanks. What is the purpose of this flag?

**Comment by JBorrow** [comment]
This flag ensures that the smoothing lengths are exactly correct at the start of the simulation. It is helpful if you put approximate smoothing lengths in the initial conditions. More here: http://swift.dur.ac.uk/docs/ParameterFiles/parameter_description.html#initial-conditions

**Comment by yonatansmn** [comment]
Great. How about adding RunTime parameteres group? I understand how to do it manually, just wanted to know if it's possible directly with SWIFTWriter

**Comment by JBorrow** [comment]
Sorry, which parameters do you mean?

**Comment by JBorrow** [comment]
All parameters that are specified at run time should be done so through either the flags passed to the SWIFT binary, or through the use of the parameter file.

**Comment by yonatansmn** [comment]
I follow the Uranus impact example. Its h5 file includes 4 groups: Header, PartType0, RuntimePars and Units

**Comment by JBorrow** [comment]
Don't worry about `RuntimePars`, that must be there for compatibility with the other codes. That field is ignored by SWIFT completely (if I remember correctly, this is for compatibility with the P-Gadget3 code).

**Comment by yonatansmn** [comment]
OK. Thanks.
