### ISSUE TITLE
Performance Regression in Visualistion

### ISSUE THREAD

**Issue by Fonotec** [SWIFTSIM/swiftsimio#55]
Changing from swiftsimio 3.1.0 to 3.1.2 I get that the code runs significantly slower as before. This is at least a difference of a factor of 10. This was all run on cosma7. 

In the isolated-galaxy-plotting repository I have a script that did very bad called:  edge_on_gas_and_stars.py

Let me know if you want to know something else.

**Comment by JBorrow** [comment]
Hi Folkert, did we figure out this was a problem with the `numba` version you were running?

**Comment by Fonotec** [comment]
Yes, this is related to the numba version I was running, so if I use a newer version I don't have the problem.

**Comment by JBorrow** [comment]
Ok, I don't think there is much we can do here apart from require numba as a dependency but I really don't want to do that - so unfortunately I think we're just going to have to live with this for now until most people upgrade numba.
