### ISSUE TITLE
to_physical() method of particle arrays correcting a factors in wrong direction

### ISSUE THREAD

**Issue by wmfw23** [SWIFTSIM/swiftsimio#84]
Expansion factor corrections seem to be correcting values in the wrong direction, (i.e. at higher z physical distances are a factor larger by a factor `1/a` rather than smaller by `a`). This is true in general for other units, i.e. a factor `a^-n` is applied rather than `a^n`. Related, the test in `swiftsimio/tests/test_physical_conversion.py` is upside down (yielding physical coords > comoving coords)

**Comment by JBorrow** [comment]
Fixed in master
