### ISSUE TITLE
Exception when loading test volume

### ISSUE THREAD

**Issue by fwojtan** [SWIFTSIM/swiftsimio#95]
I noticed that when loading the test volume (http://virgodb.cosma.dur.ac.uk/swift-webstorage/IOExamples/cosmo_volume_example.hdf5) using `data = load("cosmo_volume_example.hdf5")` an IndexError is thrown when creating a `MassTable` in `SWIFTMetadata.postprocess_header()`.  

I think this might be due to the most recent version having 7 particle types while the test volume only has 6. As a workaround for now I've removed the sixth entries of the three arrays in particle_types.py:
```
import swiftsimio.metadata.particle as swp

swp.particle_name_underscores.pop(6)
swp.particle_name_class.pop(6)
swp.particle_name_text.pop(6)
```
This seemed to work as I could then load the snapshot as expected. I'm still just trying to figure out the SWIFT basics but hopefully this is helpful!

Cheers, F

**Comment by MatthieuSchaller** [comment]
ugggh.... yes... 

Don't we read the number of types from the header and default to 6?
